import { ColorCode, StatusCode } from './enums.js';

export const ReasonPhrases = {
  [StatusCode.ACCEPTED]: 'Accepted',
  [StatusCode.BAD_GATEWAY]: 'Bad Gateway',
  [StatusCode.BAD_REQUEST]: 'Bad Request',
  [StatusCode.CONFLICT]: 'Conflict',
  [StatusCode.CONTINUE]: 'Continue',
  [StatusCode.CREATED]: 'Created',
  [StatusCode.EXPECTATION_FAILED]: 'Expectation Failed',
  [StatusCode.FAILED_DEPENDENCY]: 'Failed Dependency',
  [StatusCode.FORBIDDEN]: 'Forbidden',
  [StatusCode.GATEWAY_TIMEOUT]: 'Gateway Timeout',
  [StatusCode.GONE]: 'Gone',
  [StatusCode.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP Version Not Supported',
  [StatusCode.IM_A_TEAPOT]: "I'm a teapot",
  [StatusCode.INSUFFICIENT_SPACE_ON_RESOURCE]: 'Insufficient Space on Resource',
  [StatusCode.INSUFFICIENT_STORAGE]: 'Insufficient Storage',
  [StatusCode.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [StatusCode.LENGTH_REQUIRED]: 'Length Required',
  [StatusCode.LOCKED]: 'Locked',
  [StatusCode.METHOD_FAILURE]: 'Method Failure',
  [StatusCode.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [StatusCode.MOVED_PERMANENTLY]: 'Moved Permanently',
  [StatusCode.MOVED_TEMPORARILY]: 'Moved Temporarily',
  [StatusCode.MULTI_STATUS]: 'Multi-Status',
  [StatusCode.MULTIPLE_CHOICES]: 'Multiple Choices',
  [StatusCode.NETWORK_AUTHENTICATION_REQUIRED]: 'Network Authentication Required',
  [StatusCode.NO_CONTENT]: 'No Content',
  [StatusCode.NON_AUTHORITATIVE_INFORMATION]: 'Non Authoritative Information',
  [StatusCode.NOT_ACCEPTABLE]: 'Not Acceptable',
  [StatusCode.NOT_FOUND]: 'Not Found',
  [StatusCode.NOT_IMPLEMENTED]: 'Not Implemented',
  [StatusCode.NOT_MODIFIED]: 'Not Modified',
  [StatusCode.OK]: 'OK',
  [StatusCode.PARTIAL_CONTENT]: 'Partial Content',
  [StatusCode.PAYMENT_REQUIRED]: 'Payment Required',
  [StatusCode.PERMANENT_REDIRECT]: 'Permanent Redirect',
  [StatusCode.PRECONDITION_FAILED]: 'Precondition Failed',
  [StatusCode.PRECONDITION_REQUIRED]: 'Precondition Required',
  [StatusCode.PROCESSING]: 'Processing',
  [StatusCode.EARLY_HINTS]: 'Early Hints',
  [StatusCode.UPGRADE_REQUIRED]: 'Upgrade Required',
  [StatusCode.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy Authentication Required',
  [StatusCode.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request Header Fields Too Large',
  [StatusCode.REQUEST_TIMEOUT]: 'Request Timeout',
  [StatusCode.REQUEST_TOO_LONG]: 'Request Entity Too Large',
  [StatusCode.REQUEST_URI_TOO_LONG]: 'Request-URI Too Long',
  [StatusCode.REQUESTED_RANGE_NOT_SATISFIABLE]: 'Requested Range Not Satisfiable',
  [StatusCode.RESET_CONTENT]: 'Reset Content',
  [StatusCode.SEE_OTHER]: 'See Other',
  [StatusCode.SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [StatusCode.SWITCHING_PROTOCOLS]: 'Switching Protocols',
  [StatusCode.TEMPORARY_REDIRECT]: 'Temporary Redirect',
  [StatusCode.TOO_MANY_REQUESTS]: 'Too Many Requests',
  [StatusCode.UNAUTHORIZED]: 'Unauthorized',
  [StatusCode.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable For Legal Reasons',
  [StatusCode.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [StatusCode.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported Media Type',
  [StatusCode.USE_PROXY]: 'Use Proxy',
  [StatusCode.MISDIRECTED_REQUEST]: 'Misdirected Request',
};

export const ColorCodes = {
  [ColorCode.reset]: [0, 0],

  [ColorCode.bold]: [1, 22],
  [ColorCode.dim]: [2, 22],
  [ColorCode.italic]: [3, 23],
  [ColorCode.underline]: [4, 24],
  [ColorCode.inverse]: [7, 27],
  [ColorCode.hidden]: [8, 28],
  [ColorCode.strikethrough]: [9, 29],

  [ColorCode.black]: [30, 39],
  [ColorCode.red]: [31, 39],
  [ColorCode.green]: [32, 39],
  [ColorCode.yellow]: [33, 39],
  [ColorCode.blue]: [34, 39],
  [ColorCode.magenta]: [35, 39],
  [ColorCode.cyan]: [36, 39],
  [ColorCode.white]: [37, 39],
  [ColorCode.gray]: [90, 39],
  [ColorCode.grey]: [90, 39],

  [ColorCode.brightRed]: [91, 39],
  [ColorCode.brightGreen]: [92, 39],
  [ColorCode.brightYellow]: [93, 39],
  [ColorCode.brightBlue]: [94, 39],
  [ColorCode.brightMagenta]: [95, 39],
  [ColorCode.brightCyan]: [96, 39],
  [ColorCode.brightWhite]: [97, 39],

  [ColorCode.bgBlack]: [40, 49],
  [ColorCode.bgRed]: [41, 49],
  [ColorCode.bgGreen]: [42, 49],
  [ColorCode.bgYellow]: [43, 49],
  [ColorCode.bgBlue]: [44, 49],
  [ColorCode.bgMagenta]: [45, 49],
  [ColorCode.bgCyan]: [46, 49],
  [ColorCode.bgWhite]: [47, 49],
  [ColorCode.bgGray]: [100, 49],
  [ColorCode.bgGrey]: [100, 49],

  [ColorCode.bgBrightRed]: [101, 49],
  [ColorCode.bgBrightGreen]: [102, 49],
  [ColorCode.bgBrightYellow]: [103, 49],
  [ColorCode.bgBrightBlue]: [104, 49],
  [ColorCode.bgBrightMagenta]: [105, 49],
  [ColorCode.bgBrightCyan]: [106, 49],
  [ColorCode.bgBrightWhite]: [107, 49],
};
