import { StatusCode } from './enums';

export const ReasonPhrases = {
  [StatusCode.ACCEPTED]: 'Accepted',
  [StatusCode.BAD_GATEWAY]: 'Bad Gateway',
  [StatusCode.BAD_REQUEST]: 'Bad Request',
  [StatusCode.CONFLICT]: 'Conflict',
  [StatusCode.CONTINUE]: 'Continue',
  [StatusCode.CREATED]: 'Created',
  [StatusCode.EXPECTATION_FAILED]: 'Expectation Failed',
  [StatusCode.FAILED_DEPENDENCY]: 'Failed Dependency',
  [StatusCode.FORBIDDEN]: 'Forbidden',
  [StatusCode.GATEWAY_TIMEOUT]: 'Gateway Timeout',
  [StatusCode.GONE]: 'Gone',
  [StatusCode.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP Version Not Supported',
  [StatusCode.IM_A_TEAPOT]: "I'm a teapot",
  [StatusCode.INSUFFICIENT_SPACE_ON_RESOURCE]: 'Insufficient Space on Resource',
  [StatusCode.INSUFFICIENT_STORAGE]: 'Insufficient Storage',
  [StatusCode.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [StatusCode.LENGTH_REQUIRED]: 'Length Required',
  [StatusCode.LOCKED]: 'Locked',
  [StatusCode.METHOD_FAILURE]: 'Method Failure',
  [StatusCode.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [StatusCode.MOVED_PERMANENTLY]: 'Moved Permanently',
  [StatusCode.MOVED_TEMPORARILY]: 'Moved Temporarily',
  [StatusCode.MULTI_STATUS]: 'Multi-Status',
  [StatusCode.MULTIPLE_CHOICES]: 'Multiple Choices',
  [StatusCode.NETWORK_AUTHENTICATION_REQUIRED]: 'Network Authentication Required',
  [StatusCode.NO_CONTENT]: 'No Content',
  [StatusCode.NON_AUTHORITATIVE_INFORMATION]: 'Non Authoritative Information',
  [StatusCode.NOT_ACCEPTABLE]: 'Not Acceptable',
  [StatusCode.NOT_FOUND]: 'Not Found',
  [StatusCode.NOT_IMPLEMENTED]: 'Not Implemented',
  [StatusCode.NOT_MODIFIED]: 'Not Modified',
  [StatusCode.OK]: 'OK',
  [StatusCode.PARTIAL_CONTENT]: 'Partial Content',
  [StatusCode.PAYMENT_REQUIRED]: 'Payment Required',
  [StatusCode.PERMANENT_REDIRECT]: 'Permanent Redirect',
  [StatusCode.PRECONDITION_FAILED]: 'Precondition Failed',
  [StatusCode.PRECONDITION_REQUIRED]: 'Precondition Required',
  [StatusCode.PROCESSING]: 'Processing',
  [StatusCode.EARLY_HINTS]: 'Early Hints',
  [StatusCode.UPGRADE_REQUIRED]: 'Upgrade Required',
  [StatusCode.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy Authentication Required',
  [StatusCode.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request Header Fields Too Large',
  [StatusCode.REQUEST_TIMEOUT]: 'Request Timeout',
  [StatusCode.REQUEST_TOO_LONG]: 'Request Entity Too Large',
  [StatusCode.REQUEST_URI_TOO_LONG]: 'Request-URI Too Long',
  [StatusCode.REQUESTED_RANGE_NOT_SATISFIABLE]: 'Requested Range Not Satisfiable',
  [StatusCode.RESET_CONTENT]: 'Reset Content',
  [StatusCode.SEE_OTHER]: 'See Other',
  [StatusCode.SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [StatusCode.SWITCHING_PROTOCOLS]: 'Switching Protocols',
  [StatusCode.TEMPORARY_REDIRECT]: 'Temporary Redirect',
  [StatusCode.TOO_MANY_REQUESTS]: 'Too Many Requests',
  [StatusCode.UNAUTHORIZED]: 'Unauthorized',
  [StatusCode.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable For Legal Reasons',
  [StatusCode.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [StatusCode.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported Media Type',
  [StatusCode.USE_PROXY]: 'Use Proxy',
  [StatusCode.MISDIRECTED_REQUEST]: 'Misdirected Request',
};
